import { TFormSchema } from './../types/FormSchemaType';
export const defaultValues: TFormSchema[] = [
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'TypeScript',
    iconName: 'typescript',
    logoColor: '#3178C6',
    leftSideColor: '#24292E',
    rightSideColor: '#3178C6',
    link: 'https://typescriptlang.org',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'Javascript',
    iconName: 'javascript',
    logoColor: '#F0DB4F',
    leftSideColor: '#242216',
    rightSideColor: '#F0DB4F',
    link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'HTML5',
    iconName: 'html5',
    logoColor: '#e34c26',
    leftSideColor: '#24292E',
    rightSideColor: '#e34c26',
    link: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'MARKDOWN',
    iconName: 'markdown',
    logoColor: '#000000',
    leftSideColor: '#DDDDDD',
    rightSideColor: '#000000',
    link: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'CSS3',
    iconName: 'css3',
    logoColor: '#264de4',
    leftSideColor: '#112163',
    rightSideColor: '#264de4',
    link: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'NodeJS',
    iconName: 'nodedotjs',
    logoColor: '#68A063',
    leftSideColor: '#3F613C',
    rightSideColor: '#68A063',
    link: 'https://nodejs.org/en/',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'React',
    iconName: 'react',
    logoColor: '#61DBFB',
    leftSideColor: '#1A1C1E',
    rightSideColor: '#24292E',
    link: 'https://reactjs.org/docs/getting-started.html',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'Github',
    iconName: 'github',
    logoColor: '#FAFBFC',
    leftSideColor: '#24292E',
    rightSideColor: '#2B3137',
    link: 'https://github.com/',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'git',
    iconName: 'git',
    logoColor: '#F54D27',
    leftSideColor: '#453D36',
    rightSideColor: '#e34c26',
    link: 'https://git-scm.com/',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'sass',
    iconName: 'sass',
    logoColor: '#C76494',
    leftSideColor: '#874464',
    rightSideColor: '#C76494',
    link: 'https://sass-lang.com/',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'tailwindcss',
    iconName: 'tailwindcss',
    logoColor: '#01B7D6',
    leftSideColor: '#004A57',
    rightSideColor: '#01B7D6',
    link: 'https://tailwindcss.com/',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'npm',
    iconName: 'npm',
    logoColor: '#CB3837',
    leftSideColor: '#8C2626',
    rightSideColor: '#CB3837',
    link: 'https://www.npmjs.com/',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'yarn',
    iconName: 'yarn',
    logoColor: '#2B8AB5',
    leftSideColor: '#1C5975',
    rightSideColor: '#2B8AB5',
    link: 'https://yarnpkg.com/',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'pnpm',
    iconName: 'pnpm',
    logoColor: '#F1A800',
    leftSideColor: '#4C4C4C',
    rightSideColor: '#F1A800',
    link: 'https://pnpm.io/',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'mongodb',
    iconName: 'mongodb',
    logoColor: '#00ED64',
    leftSideColor: '#001E2B',
    rightSideColor: '#00ED64',
    link: 'https://www.mongodb.com/',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'prisma',
    iconName: 'prisma',
    logoColor: '#DDDDDD',
    leftSideColor: '#0C3249',
    rightSideColor: '#0C3249',
    link: 'https://www.prisma.io/',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'rust',
    iconName: 'rust',
    logoColor: '#A53C15',
    leftSideColor: '#66250D',
    rightSideColor: '#A53C15',
    link: 'https://www.rust-lang.org/',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'python',
    iconName: 'python',
    logoColor: '#C9B559',
    leftSideColor: '#142736',
    rightSideColor: '#4584B6',
    link: 'https://www.python.org/',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'php',
    iconName: 'php',
    logoColor: '#484C89',
    leftSideColor: '#272A4A',
    rightSideColor: '#484C89',
    link: 'https://www.php.net/',
  },
];
