import { TFormSchema } from './../types/FormSchemaType';
export const defaultValues: TFormSchema[] = [
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'TypeScript',
    iconName: 'typescript',
    logoColor: '#3178C6',
    leftSideColor: '#24292E',
    rightSideColor: '#3178C6',
    link: 'https://typescriptlang.org',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'Javascript',
    iconName: 'javascript',
    logoColor: '#F0DB4F',
    leftSideColor: '#242216',
    rightSideColor: '#F0DB4F',
    link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'HTML',
    iconName: 'html5',
    logoColor: '#e34c26',
    leftSideColor: '#24292E',
    rightSideColor: '#e34c26',
    link: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'CSS',
    iconName: 'css3',
    logoColor: '#264de4',
    leftSideColor: '#112163',
    rightSideColor: '#264de4',
    link: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'NodeJS',
    iconName: 'nodedotjs',
    logoColor: '#68A063',
    leftSideColor: '#3F613C',
    rightSideColor: '#68A063',
    link: 'https://nodejs.org/en/',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'React',
    iconName: 'react',
    logoColor: '#61DBFB',
    leftSideColor: '#1A1C1E',
    rightSideColor: '#24292E',
    link: 'https://reactjs.org/docs/getting-started.html',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'Github',
    iconName: 'github',
    logoColor: '#FAFBFC',
    leftSideColor: '#24292E',
    rightSideColor: '#2B3137',
    link: 'https://github.com/',
  },
  {
    badgeStyle: 'for-the-badge',
    badgeText: 'git',
    iconName: 'git',
    logoColor: '#F54D27',
    leftSideColor: '#453D36',
    rightSideColor: '#e34c26',
    link: 'https://git-scm.com/',
  },
];
